# Generated by Django 3.2.5 on 2022-09-26 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('empfname', models.CharField(max_length=100)),
                ('emplname', models.CharField(max_length=100)),
                ('empdept', models.CharField(max_length=100)),
                ('emplocation', models.CharField(max_length=100, null=True)),
                ('empphone', models.CharField(max_length=15, unique=True)),
                ('empemail', models.CharField(max_length=100, unique=True)),
                ('emppassword', models.CharField(max_length=125)),
                ('empassignstatus', models.BooleanField(null=True)),
                ('empintassignstatus', models.BooleanField(null=True)),
                ('last_login', models.DateTimeField(null=True)),
                ('last_logout', models.DateTimeField(null=True)),
                ('languages', django_mysql.models.ListCharField(models.CharField(max_length=20), max_length=140, null=True, size=6)),
                ('firstlan', models.CharField(max_length=255, null=True)),
                ('seclan', models.CharField(max_length=255, null=True)),
                ('thirdlan', models.CharField(max_length=255, null=True)),
                ('source', django_mysql.models.ListCharField(models.CharField(max_length=20), default='Organic', max_length=140, size=6)),
                ('columns_prospect', django_mysql.models.ListCharField(models.CharField(max_length=40), max_length=1250, null=True, size=25)),
                ('columns_investor', django_mysql.models.ListCharField(models.CharField(max_length=40), max_length=1250, null=True, size=25)),
                ('empnickname', models.CharField(max_length=100, null=True)),
                ('profile_pic', models.ImageField(null=True, upload_to='ProfilePics/')),
                ('empcreateddt', models.DateTimeField(auto_now_add=True)),
                ('empupdateddt', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_by', models.IntegerField(null=True)),
                ('reporting_to', models.CharField(max_length=100, null=True)),
                ('cap', models.IntegerField(null=True)),
                ('cap_reached', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('join_date', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.CharField(max_length=100)),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='app.prospect')),
            ],
        ),
    ]
